name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Install protoc, protoc-gen-go
        run: sudo apt install protobuf-compiler golang-goprotobuf-dev

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.12.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazelisk"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazelisk"

      - name: Build Release Assets
        run: |
          ${GITHUB_WORKSPACE}/bin/bazelisk build :doubak
          mkdir releases
          cp ./bazel-bin/doubak_/doubak releases/doubak-${{ steps.tagName.outputs.tag }}-linux-amd64

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ steps.tagName.outputs.tag }}
          tag_name: ${{ steps.tagName.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            Automatic Release by GitHub Workflow
          token: ${{ secrets.GITHUB_TOKEN }}
          files: releases/doubak-${{ steps.tagName.outputs.tag }}-linux-amd64
